"""The cloud half of the site agent's sync.

A pharmacy's internet is not guaranteed, and a point of sale that stops
selling when the connection drops is worthless. So the agent journals
locally and replays when it can — which makes **idempotency the whole
contract here**, not a nicety.

Every envelope carries a client-generated id. The server records what it
has already applied and returns the same answer for a repeat rather than
applying it twice. That is what makes the agent free to retry blindly,
which in turn is what lets it be simple.

Order matters within a device and not between devices: one till's
sequence must replay in order, but two tills are independent and waiting
for one to reconnect would stop the other selling.
"""

from __future__ import annotations

from dataclasses import dataclass

from django.db import models, transaction
from django.utils import timezone

from core import audit
from core.exceptions import DomainError
from core.models import BaseModel, Organization, TenantModel, User


class SyncStatus(models.TextChoices):
    APPLIED = "APPLIED", "Applied"
    DUPLICATE = "DUPLICATE", "Already applied"
    #: Kept, not discarded. A payload the server could not apply is
    #: evidence of a bug, and dropping it loses the only copy.
    FAILED = "FAILED", "Failed"


class Device(TenantModel):
    """One agent installation.

    A pharmacy runs one per site, sometimes per till. Registered rather
    than implicit so an unknown device is refused instead of silently
    creating a new journal — a typo'd id would otherwise look like a new
    till and its sequence would start from nothing.
    """

    code = models.CharField(max_length=60)
    name = models.CharField(max_length=120, blank=True)
    branch = models.ForeignKey(
        "core.Branch", null=True, blank=True, on_delete=models.PROTECT, related_name="+"
    )
    location = models.ForeignKey(
        "inventory.Location", null=True, blank=True, on_delete=models.PROTECT,
        related_name="+",
    )

    is_active = models.BooleanField(default=True)
    last_seen_at = models.DateTimeField(null=True, blank=True)
    agent_version = models.CharField(max_length=20, blank=True)

    class Meta:
        db_table = "core_device"
        constraints = [
            models.UniqueConstraint(
                fields=["organization", "code"], name="uq_device_code"
            ),
        ]

    def __str__(self) -> str:
        return self.name or self.code


class SyncEnvelope(BaseModel):
    """One replayed operation, and what happened to it.

    The row exists so a retry can be answered without re-applying. It is
    append-only in spirit: the status moves once, from nothing to a
    result, and is never rewritten.
    """

    organization = models.ForeignKey(
        "core.Organization", on_delete=models.PROTECT, related_name="+"
    )
    device = models.ForeignKey(Device, on_delete=models.PROTECT, related_name="envelopes")

    #: Generated by the agent. The idempotency key for the whole system.
    client_id = models.CharField(max_length=64)
    #: Per-device monotonic counter, so gaps are visible.
    sequence = models.BigIntegerField(default=0)
    kind = models.CharField(max_length=40)
    payload = models.JSONField(default=dict)

    status = models.CharField(max_length=12, choices=SyncStatus.choices)
    result = models.JSONField(null=True, blank=True)
    error = models.TextField(blank=True)

    #: When the agent recorded it, not when we received it. A sale that
    #: happened during an outage belongs to the hour it happened in.
    occurred_at = models.DateTimeField()
    received_at = models.DateTimeField(default=timezone.now)

    class Meta:
        db_table = "core_sync_envelope"
        ordering = ["device", "sequence"]
        constraints = [
            models.UniqueConstraint(
                fields=["organization", "client_id"], name="uq_sync_client_id"
            ),
        ]
        indexes = [
            models.Index(fields=["device", "sequence"]),
            models.Index(fields=["organization", "status"]),
        ]

    def __str__(self) -> str:
        return f"{self.kind} {self.client_id[:8]}"


@dataclass(frozen=True)
class Applied:
    envelope: SyncEnvelope
    replayed: bool


#: What an agent may replay. A whitelist rather than a dispatch on
#: whatever the payload names: the sync endpoint is the least trusted
#: input in the system, and it must not be able to reach an arbitrary
#: service function.
HANDLERS: dict[str, str] = {
    "sale": "core.sync.apply_sale",
    "temperature": "core.sync.apply_temperature",
    "stock_count": "core.sync.apply_stock_count",
}


@transaction.atomic
def apply_envelope(
    *,
    organization: Organization,
    device: Device,
    client_id: str,
    kind: str,
    payload: dict,
    occurred_at,
    sequence: int = 0,
    performed_by: User | None = None,
) -> Applied:
    """Apply one operation, exactly once.

    A repeat returns the stored result rather than doing the work again.
    This is what lets the agent retry without reasoning about what got
    through — and an agent that has to reason about that is an agent that
    will get it wrong during the one outage that matters.
    """
    existing = SyncEnvelope.objects.filter(
        organization=organization, client_id=client_id
    ).first()
    if existing is not None:
        return Applied(existing, replayed=True)

    if kind not in HANDLERS:
        raise DomainError(f"Unknown sync kind '{kind}'.", code="unknown_sync_kind")

    envelope = SyncEnvelope(
        organization=organization,
        device=device,
        client_id=client_id,
        sequence=sequence,
        kind=kind,
        payload=payload,
        occurred_at=occurred_at,
        status=SyncStatus.APPLIED,
    )

    from django.utils.module_loading import import_string

    handler = import_string(HANDLERS[kind])
    try:
        # A savepoint: a payload that fails must be recorded as failed,
        # not vanish with the transaction that tried to apply it.
        with transaction.atomic():
            envelope.result = handler(
                organization=organization,
                device=device,
                payload=payload,
                occurred_at=occurred_at,
                performed_by=performed_by,
            )
    except Exception as exc:
        envelope.status = SyncStatus.FAILED
        envelope.error = f"{type(exc).__name__}: {exc}"[:2000]

    envelope.save()

    device.last_seen_at = timezone.now()
    device.save(update_fields=["last_seen_at", "modified_at"])

    if envelope.status == SyncStatus.FAILED:
        audit.record(
            action="core.sync.failed",
            subject=envelope,
            actor=performed_by,
            after={"kind": kind, "device": device.code, "error": envelope.error},
            organization=organization,
        )
    return Applied(envelope, replayed=False)


# --------------------------------------------------------------------------
# Handlers
# --------------------------------------------------------------------------


def apply_temperature(*, organization, device, payload, occurred_at, performed_by):
    """A buffered batch of sensor readings.

    Each reading is idempotent on its own timestamp, so a re-sent buffer
    overlapping one already received adds nothing.
    """
    from datetime import datetime

    from inventory.telemetry import Sensor, record_reading

    sensor = Sensor.objects.filter(
        organization=organization, device_code=payload["sensor"]
    ).first()
    if sensor is None:
        raise DomainError(
            f"Unknown sensor '{payload['sensor']}'.", code="unknown_sensor"
        )

    stored = 0
    excursions = 0
    for entry in payload.get("readings", []):
        result = record_reading(
            sensor=sensor,
            celsius=entry["celsius"],
            recorded_at=datetime.fromisoformat(entry["at"]),
            # Anything replayed through sync was held on the device.
            was_buffered=True,
            performed_by=performed_by,
        )
        if not result.duplicate:
            stored += 1
        if result.opened:
            excursions += 1

    return {"stored": stored, "excursions_opened": excursions}


def apply_sale(*, organization, device, payload, occurred_at, performed_by):
    """A sale journalled while the connection was down.

    Rebuilt through the ordinary service path rather than inserted: an
    offline sale must meet the same prescription gate, the same FEFO
    allocation and the same controlled register as one rung up live.
    Trusting the device's own totals would make the offline path the way
    to bypass every rule.
    """
    from catalog.models import Product, UnitOfMeasure
    from inventory.models import Location
    from sales import payments, services as sales

    location = Location.objects.get(organization=organization, pk=payload["location"])
    branch = location.branch
    if branch is None:
        raise DomainError(
            f"{location.name} is not attached to a branch.", code="location_has_no_branch"
        )

    sale = sales.start_sale(
        organization=organization,
        branch=branch,
        location=location,
        cashier=performed_by,
    )
    sale.occurred_at = occurred_at
    sale.save(update_fields=["occurred_at"])

    for line in payload.get("lines", []):
        product = Product.objects.get(organization=organization, pk=line["product"])
        sales.add_line(
            sale=sale,
            product=product,
            quantity=line["quantity"],
            uom=UnitOfMeasure.objects.get(product=product, code=line["uom_code"]),
            unit_price=line["unit_price"],
            discount=line.get("discount", 0),
        )

    # Tender before posting. Money changed hands at the till during the
    # outage; a sale replayed without it would sit in PENDING_PAYMENT and
    # day end would report a shortfall that does not exist.
    for tender in payload.get("payments", []):
        payments.take_payment(
            sale=sale,
            method=tender["method"],
            amount=int(tender["amount"]),
            performed_by=performed_by,
            provider_code=tender.get("provider", ""),
            phone=tender.get("phone", ""),
        )

    sales.complete_sale(
        sale=sale,
        performed_by=performed_by,
        idempotency_key=payload.get("client_id", ""),
    )
    return {"sale": str(sale.id), "number": sale.number, "status": sale.status}


def apply_stock_count(*, organization, device, payload, occurred_at, performed_by):
    """A stocktake done on the floor, with the difference as a movement.

    The count itself is not the record — the adjustment is. Writing a
    counted figure straight into a balance would be the one thing the
    ledger exists to prevent.
    """
    from core.quantity import from_base
    from inventory import services as inventory
    from inventory.models import Batch, Location, MovementKind

    location = Location.objects.get(organization=organization, pk=payload["location"])
    adjustments = 0

    for entry in payload.get("counts", []):
        batch = Batch.objects.get(organization=organization, pk=entry["batch"])
        on_hand = inventory.balance_for(
            organization=organization, product=batch.product, location=location
        )
        difference = int(entry["counted_base"]) - on_hand
        if difference == 0:
            continue
        inventory.post_movement(
            organization=organization,
            location=location,
            batch=batch,
            kind=MovementKind.ADJUSTMENT,
            quantity=from_base(difference, batch.product.base_uom),
            performed_by=performed_by,
            reason=entry.get("reason", "Stock count"),
        )
        adjustments += 1

    return {"adjustments": adjustments}
