# Generated by Django 5.1.5 on 2026-08-12 17:48

import core.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dosage_form',
            field=models.CharField(blank=True, choices=[('TABLET', 'Tablet'), ('CAPSULE', 'Capsule'), ('SYRUP', 'Syrup'), ('SUSPENSION', 'Suspension'), ('INJECTION', 'Injection'), ('INFUSION', 'Infusion'), ('CREAM', 'Cream'), ('OINTMENT', 'Ointment'), ('GEL', 'Gel'), ('DROPS', 'Drops'), ('INHALER', 'Inhaler'), ('SUPPOSITORY', 'Suppository'), ('PATCH', 'Patch'), ('POWDER', 'Powder'), ('SACHET', 'Sachet'), ('DEVICE', 'Device'), ('OTHER', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='light_sensitive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='moisture_sensitive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='pack_dimensions',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='reorder_point_base',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='route',
            field=models.CharField(blank=True, choices=[('ORAL', 'Oral'), ('TOPICAL', 'Topical'), ('INTRAVENOUS', 'Intravenous'), ('INTRAMUSCULAR', 'Intramuscular'), ('SUBCUTANEOUS', 'Subcutaneous'), ('INHALATION', 'Inhalation'), ('OPHTHALMIC', 'Ophthalmic'), ('OTIC', 'Otic'), ('NASAL', 'Nasal'), ('RECTAL', 'Rectal'), ('VAGINAL', 'Vaginal'), ('NOT_APPLICABLE', 'Not applicable')], max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='storage_max_c',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='storage_min_c',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='strength',
            field=models.CharField(blank=True, help_text='e.g. "500mg", "10mg/ml"', max_length=60),
        ),
        migrations.AddField(
            model_name='product',
            name='unit_weight_g',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.UUIDField(default=core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('name', models.CharField(max_length=150)),
                ('country_of_origin', models.CharField(blank=True, max_length=80)),
                ('gmp_certified', models.BooleanField(default=True)),
                ('gmp_expiry', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.organization')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'catalog_manufacturer',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.manufacturer'),
        ),
        migrations.AddConstraint(
            model_name='manufacturer',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='uq_manufacturer_name'),
        ),
    ]
