# Generated by Django 5.1.5 on 2026-08-12 22:34

import core.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_productimage'),
        ('core', '0003_controlledquota'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalAttribute',
            fields=[
                ('id', models.UUIDField(default=core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('kind', models.CharField(choices=[('MIN_AGE_YEARS', 'Minimum age, years'), ('MAX_AGE_YEARS', 'Maximum age, years'), ('MAX_DAILY_DOSE_BASE', 'Maximum daily dose, base units'), ('PREGNANCY_RESTRICTED', 'Restricted in pregnancy'), ('ACTIVE_INGREDIENT', 'Active ingredient')], max_length=24)),
                ('value_number', models.BigIntegerField(blank=True, null=True)),
                ('value_text', models.CharField(blank=True, max_length=200)),
                ('source', models.CharField(help_text='Where this came from — SmPC, Rwanda FDA, monograph.', max_length=200)),
                ('source_reference', models.CharField(blank=True, max_length=200)),
                ('effective_from', models.DateField(default=django.utils.timezone.localdate)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.organization')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_attributes', to='catalog.product')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'catalog_clinical_attribute',
                'ordering': ['kind', '-effective_from'],
                'indexes': [models.Index(fields=['product', 'kind', 'effective_from'], name='catalog_cli_product_3f839a_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('source', ''), _negated=True), name='ck_clinical_source_required')],
            },
        ),
    ]
