# Generated by Django 5.1.5 on 2026-08-11 17:40

import core.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiscalRecord',
            fields=[
                ('id', models.UUIDField(default=core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('FAILED', 'Failed')], default='QUEUED', max_length=12)),
                ('backend', models.CharField(help_text='mock | vsdc', max_length=20)),
                ('receipt_number', models.CharField(blank=True, max_length=60)),
                ('fiscal_signature', models.CharField(blank=True, max_length=200)),
                ('device_id', models.CharField(blank=True, max_length=60)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=60)),
                ('error_message', models.TextField(blank=True)),
                ('attempts', models.IntegerField(default=0)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.organization')),
                ('sale', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='fiscal_record', to='sales.sale')),
            ],
            options={
                'db_table': 'fiscal_record',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'status'], name='fiscal_reco_organiz_39e04e_idx'), models.Index(fields=['organization', '-created_at'], name='fiscal_reco_organiz_9efcc8_idx')],
            },
        ),
    ]
