# Generated by Django 5.1.5 on 2026-08-12 10:40

import core.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('commerce', '0001_initial'),
        ('core', '0001_initial'),
        ('inventory', '0002_alter_stockmovement_kind'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.UUIDField(default=core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('number', models.CharField(blank=True, max_length=30)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('DISPATCHED', 'Dispatched')], default='DRAFT', max_length=20)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('carrier', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'db_table': 'commerce_shipment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentLine',
            fields=[
                ('id', models.UUIDField(default=core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('quantity_base', models.BigIntegerField()),
                ('batch_number', models.CharField(max_length=60)),
                ('expiry_date', models.DateField()),
            ],
            options={
                'db_table': 'commerce_shipment_line',
            },
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='dispatched_base',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('CONFIRMED', 'Confirmed'), ('PARTIALLY_DISPATCHED', 'Partially dispatched'), ('DISPATCHED', 'Dispatched'), ('PARTIALLY_RECEIVED', 'Partially received'), ('RECEIVED', 'Received'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderline',
            constraint=models.CheckConstraint(condition=models.Q(('dispatched_base__gte', 0)), name='ck_po_dispatched_nonneg'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shipment',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shipment',
            name='from_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.location'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shipment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='commerce.purchaseorder'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.organization'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shipmentline',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.batch'),
        ),
        migrations.AddField(
            model_name='shipmentline',
            name='order_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispatches', to='commerce.purchaseorderline'),
        ),
        migrations.AddField(
            model_name='shipmentline',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.product'),
        ),
        migrations.AddField(
            model_name='shipmentline',
            name='shipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='commerce.shipment'),
        ),
        migrations.AddField(
            model_name='shipmentline',
            name='uom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.unitofmeasure'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['organization', 'status'], name='commerce_sh_organiz_734082_idx'),
        ),
        migrations.AddConstraint(
            model_name='shipment',
            constraint=models.UniqueConstraint(condition=models.Q(('number', ''), _negated=True), fields=('organization', 'number'), name='uq_shipment_number'),
        ),
        migrations.AddConstraint(
            model_name='shipmentline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_base__gt', 0)), name='ck_shipment_line_qty'),
        ),
    ]
