# Generated by Django 5.1.5 on 2026-08-12 17:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('commerce', '0002_shipment_shipmentline_and_more'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorlisting',
            name='committed_base',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vendorlisting',
            name='offered_base',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Awaiting internal approval'), ('REJECTED', 'Rejected internally'), ('SUBMITTED', 'Sent to depot'), ('CONFIRMED', 'Approved by depot'), ('PREPARING', 'Being prepared'), ('PARTIALLY_DISPATCHED', 'Partially dispatched'), ('DISPATCHED', 'Dispatched'), ('PARTIALLY_RECEIVED', 'Partially received'), ('RECEIVED', 'Received'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='vendorlisting',
            constraint=models.CheckConstraint(condition=models.Q(('offered_base__gte', 0)), name='ck_listing_offered_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='vendorlisting',
            constraint=models.CheckConstraint(condition=models.Q(('committed_base__gte', 0)), name='ck_listing_committed_nonneg'),
        ),
    ]
