# Generated by Django 5.1.5 on 2026-08-12 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0003_vendorlisting_committed_base_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceipt',
            name='clearing_fees',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='customs_duty',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='freight',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='fx_rate_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='fx_rate_is_official',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='fx_rate_scaled',
            field=models.BigIntegerField(default=10000),
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='invoice_currency',
            field=models.CharField(default='RWF', max_length=3),
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='other_charges',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='goodsreceiptline',
            name='landed_cost_share',
            field=models.BigIntegerField(default=0),
        ),
    ]
