# Generated by Django 5.1.5 on 2026-08-12 18:40

import core.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_productimage'),
        ('commerce', '0004_goodsreceipt_clearing_fees_goodsreceipt_customs_duty_and_more'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='payment_terms_days',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('number', models.CharField(blank=True, max_length=30)),
                ('kind', models.CharField(choices=[('PROFORMA', 'Proforma invoice'), ('TAX', 'Commercial tax invoice'), ('CREDIT_NOTE', 'Credit note')], default='TAX', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ISSUED', 'Issued'), ('PART_PAID', 'Partly paid'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('issued_on', models.DateField(blank=True, null=True)),
                ('due_on', models.DateField(blank=True, null=True)),
                ('payment_terms_days', models.IntegerField(default=0)),
                ('subtotal', models.BigIntegerField(default=0)),
                ('tax_total', models.BigIntegerField(default=0)),
                ('total', models.BigIntegerField(default=0)),
                ('currency', models.CharField(default='RWF', max_length=3)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_invoices', to='core.organization')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='commerce.purchaseorder')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.organization')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'commerce_invoice',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.UUIDField(default=core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.BigIntegerField()),
                ('line_subtotal', models.BigIntegerField()),
                ('tax_treatment', models.CharField(max_length=10)),
                ('tax_rate_basis_points', models.IntegerField(default=0)),
                ('tax_amount', models.BigIntegerField(default=0)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='commerce.invoice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.product')),
                ('uom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.unitofmeasure')),
            ],
            options={
                'db_table': 'commerce_invoice_line',
            },
        ),
        migrations.CreateModel(
            name='InvoicePayment',
            fields=[
                ('id', models.UUIDField(default=core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('amount', models.BigIntegerField()),
                ('method', models.CharField(default='TRANSFER', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=60)),
                ('received_on', models.DateField(default=django.utils.timezone.localdate)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='commerce.invoice')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.organization')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'commerce_invoice_payment',
                'ordering': ['-received_on'],
            },
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['organization', 'status'], name='commerce_in_organiz_ddb195_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['customer', 'status'], name='commerce_in_custome_881a23_idx'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(condition=models.Q(('number', ''), _negated=True), fields=('organization', 'number'), name='uq_invoice_number'),
        ),
        migrations.AddConstraint(
            model_name='invoicepayment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='ck_invoice_payment_positive'),
        ),
    ]
