# Generated by Django 5.1.5 on 2026-08-12 19:32

import core.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0005_purchaseorder_payment_terms_days_invoice_invoiceline_and_more'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='driver_licence',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='shipment',
            name='driver_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='shipment',
            name='received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='received_by_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='shipment',
            name='received_by_registration',
            field=models.CharField(blank=True, help_text='Council number of the receiving pharmacist.', max_length=60),
        ),
        migrations.AddField(
            model_name='shipment',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='vehicle_registration',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name='ControlledTransfer',
            fields=[
                ('id', models.UUIDField(default=core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('number', models.CharField(blank=True, max_length=30)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('received_by_name', models.CharField(blank=True, max_length=120)),
                ('received_by_registration', models.CharField(blank=True, max_length=60)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.organization')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('released_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.pharmacistregistration')),
                ('shipment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='controlled_transfer', to='commerce.shipment')),
            ],
            options={
                'db_table': 'commerce_controlled_transfer',
                'constraints': [models.UniqueConstraint(condition=models.Q(('number', ''), _negated=True), fields=('organization', 'number'), name='uq_controlled_transfer_number')],
            },
        ),
        migrations.CreateModel(
            name='OrderEvent',
            fields=[
                ('id', models.UUIDField(default=core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(blank=True, max_length=25)),
                ('to_status', models.CharField(max_length=25)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.TextField(blank=True)),
                ('document_number', models.CharField(blank=True, max_length=30)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('actor_organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.organization')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='commerce.purchaseorder')),
            ],
            options={
                'db_table': 'commerce_order_event',
                'ordering': ['occurred_at'],
                'indexes': [models.Index(fields=['order', 'occurred_at'], name='commerce_or_order_i_8f6693_idx')],
            },
        ),
    ]
