# Generated by Django 5.1.5 on 2026-08-12 19:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0007_backfill_order_events'),
        ('core', '0001_initial'),
        ('inventory', '0002_alter_stockmovement_kind'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceipt',
            name='transfer_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='transfer_id',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddConstraint(
            model_name='goodsreceipt',
            constraint=models.UniqueConstraint(condition=models.Q(('transfer_hash', ''), _negated=True), fields=('organization', 'transfer_hash'), name='uq_grn_transfer'),
        ),
    ]
