# Generated by Django 5.1.5 on 2026-08-12 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0008_goodsreceipt_transfer_hash_goodsreceipt_transfer_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderevent',
            options={'ordering': ['occurred_at', 'id']},
        ),
    ]
