# Generated by Django 5.1.5 on 2026-08-12 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0009_alter_orderevent_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='against',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='commerce.invoice'),
        ),
    ]
