# Generated by Django 5.1.5 on 2026-08-12 21:32

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0010_invoice_against'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorlisting',
            name='srp',
            field=models.BigIntegerField(blank=True, help_text='Suggested retail price, per price_uom', null=True),
        ),
        migrations.CreateModel(
            name='PriceTier',
            fields=[
                ('id', models.UUIDField(default=core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('min_quantity', models.IntegerField(help_text="In the listing's price_uom")),
                ('price', models.BigIntegerField(help_text='Per price_uom, minor units')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='commerce.vendorlisting')),
            ],
            options={
                'db_table': 'commerce_price_tier',
                'ordering': ['min_quantity'],
                'constraints': [models.UniqueConstraint(fields=('listing', 'min_quantity'), name='uq_price_tier_threshold'), models.CheckConstraint(condition=models.Q(('min_quantity__gt', 1)), name='ck_price_tier_threshold'), models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='ck_price_tier_price')],
            },
        ),
    ]
