# Generated by Django 5.1.5 on 2026-08-12 21:44

import core.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0011_vendorlisting_srp_pricetier'),
        ('core', '0003_controlledquota'),
        ('inventory', '0002_alter_stockmovement_kind'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportDocument',
            fields=[
                ('id', models.UUIDField(default=core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('kind', models.CharField(choices=[('IMPORT_LICENCE', 'Import licence or permit'), ('PROFORMA_INVOICE', 'Proforma invoice'), ('COMMERCIAL_INVOICE', 'Commercial invoice'), ('PACKING_LIST', 'Packing list'), ('BILL_OF_LADING', 'Bill of lading or air waybill'), ('CERTIFICATE_OF_ANALYSIS', 'Certificate of analysis'), ('CERTIFICATE_OF_ORIGIN', 'Certificate of origin'), ('CUSTOMS_DECLARATION', 'Customs import declaration'), ('COLD_CHAIN_LOG', 'Cold-chain temperature log')], max_length=30)),
                ('number', models.CharField(blank=True, max_length=60)),
                ('issued_by', models.CharField(blank=True, help_text='Issuing party', max_length=200)),
                ('issued_on', models.DateField(blank=True, null=True)),
                ('expires_on', models.DateField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='imports/%Y/%m/')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('min_temperature_c', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('max_temperature_c', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('breach', models.BooleanField(default=False)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='import_documents', to='inventory.batch')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.organization')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='import_documents', to='commerce.goodsreceipt')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'commerce_import_document',
                'ordering': ['kind'],
                'indexes': [models.Index(fields=['organization', 'kind'], name='commerce_im_organiz_4aa9a9_idx'), models.Index(fields=['receipt', 'kind'], name='commerce_im_receipt_d46eaa_idx')],
            },
        ),
    ]
