# Generated by Django 5.1.5 on 2026-08-11 10:19

import core.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.UUIDField(default=core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('batch_number', models.CharField(max_length=60)),
                ('manufacture_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField()),
                ('unit_cost_base', models.BigIntegerField(default=0, help_text='Landed cost per base unit, minor units')),
                ('cost_currency', models.CharField(default='RWF', max_length=3)),
                ('landed_cost_note', models.TextField(blank=True)),
                ('gtin', models.CharField(blank=True, help_text='GS1 (01)', max_length=14)),
                ('serial', models.CharField(blank=True, help_text='GS1 (21)', max_length=40)),
                ('cold_chain', models.BooleanField(default=False)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.organization')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='catalog.product')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.organization')),
            ],
            options={
                'db_table': 'inventory_batch',
                'ordering': ['expiry_date'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('kind', models.CharField(choices=[('BRANCH', 'Branch'), ('STORE', 'Store')], max_length=10)),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(max_length=20)),
                ('temperature_class', models.CharField(choices=[('AMBIENT', 'Ambient'), ('COOL_15_25', 'Cool 15–25°C'), ('COLD_2_8', 'Cold 2–8°C'), ('FROZEN', 'Frozen')], default='AMBIENT', max_length=12)),
                ('is_active', models.BooleanField(default=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='core.branch')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.organization')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='inventory.location')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'inventory_location',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockBalance',
            fields=[
                ('id', models.UUIDField(default=core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('RESERVED', 'Reserved'), ('QUARANTINED', 'Quarantined'), ('DAMAGED', 'Damaged'), ('EXPIRED', 'Expired'), ('RECALLED', 'Recalled'), ('IN_TRANSIT', 'In transit'), ('RETURNED', 'Returned')], max_length=12)),
                ('quantity_base', models.BigIntegerField(default=0)),
                ('expiry_date', models.DateField(help_text='Denormalized from batch so FEFO stays index-only')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balances', to='inventory.batch')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balances', to='inventory.location')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.organization')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.product')),
            ],
            options={
                'db_table': 'inventory_stock_balance',
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(default=core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('RESERVED', 'Reserved'), ('QUARANTINED', 'Quarantined'), ('DAMAGED', 'Damaged'), ('EXPIRED', 'Expired'), ('RECALLED', 'Recalled'), ('IN_TRANSIT', 'In transit'), ('RETURNED', 'Returned')], default='AVAILABLE', max_length=12)),
                ('kind', models.CharField(choices=[('OPENING', 'Opening balance'), ('PURCHASE_RECEIPT', 'Purchase receipt'), ('SALE', 'Sale'), ('SALE_RETURN', 'Sale return'), ('TRANSFER_OUT', 'Transfer out'), ('TRANSFER_IN', 'Transfer in'), ('ADJUSTMENT', 'Adjustment'), ('DISPOSAL', 'Disposal'), ('QUARANTINE', 'Quarantine'), ('RELEASE', 'Release'), ('RECALL', 'Recall'), ('EXPIRY_WRITE_OFF', 'Expiry write-off'), ('SUPPLIER_RETURN', 'Supplier return')], max_length=20)),
                ('quantity_base', models.BigIntegerField(help_text="Signed, in the product's base unit")),
                ('balance_after_base', models.BigIntegerField()),
                ('reason', models.TextField(blank=True)),
                ('reference', models.CharField(blank=True, help_text='Human-facing document number', max_length=60)),
                ('occurred_at', models.DateTimeField(help_text='Business time')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, help_text='System receipt time')),
                ('idempotency_key', models.CharField(max_length=64)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.batch')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.location')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.organization')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.product')),
            ],
            options={
                'db_table': 'inventory_stock_movement',
                'ordering': ['-occurred_at', '-recorded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['organization', 'expiry_date'], name='inventory_b_organiz_d9c717_idx'),
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['organization', 'product', 'expiry_date'], name='inventory_b_organiz_8531c9_idx'),
        ),
        migrations.AddConstraint(
            model_name='batch',
            constraint=models.UniqueConstraint(fields=('organization', 'product', 'supplier', 'batch_number'), name='uq_batch_number'),
        ),
        migrations.AddConstraint(
            model_name='batch',
            constraint=models.CheckConstraint(condition=models.Q(('manufacture_date__isnull', True), ('expiry_date__gt', models.F('manufacture_date')), _connector='OR'), name='ck_batch_dates'),
        ),
        migrations.AddConstraint(
            model_name='batch',
            constraint=models.CheckConstraint(condition=models.Q(('unit_cost_base__gte', 0)), name='ck_batch_cost_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='uq_location_code'),
        ),
        migrations.AddIndex(
            model_name='stockbalance',
            index=models.Index(condition=models.Q(('quantity_base__gt', 0), ('status', 'AVAILABLE')), fields=['organization', 'product', 'location', 'expiry_date'], name='idx_balance_fefo'),
        ),
        migrations.AddIndex(
            model_name='stockbalance',
            index=models.Index(fields=['organization', 'expiry_date'], name='inventory_s_organiz_a998d1_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockbalance',
            constraint=models.UniqueConstraint(fields=('location', 'batch', 'status'), name='uq_balance'),
        ),
        migrations.AddConstraint(
            model_name='stockbalance',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_base__gte', 0)), name='ck_balance_nonneg'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['organization', 'batch', 'occurred_at'], name='inventory_s_organiz_36e8dc_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['organization', 'product', '-occurred_at'], name='inventory_s_organiz_71f3c9_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['organization', 'location', 'occurred_at'], name='inventory_s_organiz_bca82b_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['batch', 'kind'], name='inventory_s_batch_i_32591e_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.UniqueConstraint(fields=('organization', 'idempotency_key'), name='uq_movement_idempotency'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_base', 0), _negated=True), name='ck_movement_qty_nonzero'),
        ),
    ]
