# Generated by Django 5.1.5 on 2026-08-12 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='kind',
            field=models.CharField(choices=[('OPENING', 'Opening balance'), ('PURCHASE_RECEIPT', 'Purchase receipt'), ('SALE', 'Sale'), ('WHOLESALE_DISPATCH', 'Wholesale dispatch'), ('SALE_RETURN', 'Sale return'), ('TRANSFER_OUT', 'Transfer out'), ('TRANSFER_IN', 'Transfer in'), ('ADJUSTMENT', 'Adjustment'), ('DISPOSAL', 'Disposal'), ('QUARANTINE', 'Quarantine'), ('RELEASE', 'Release'), ('RECALL', 'Recall'), ('EXPIRY_WRITE_OFF', 'Expiry write-off'), ('SUPPLIER_RETURN', 'Supplier return')], max_length=20),
        ),
    ]
