# Generated by Django 5.1.5 on 2026-08-13 08:03

import core.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_device_syncenvelope_device_uq_device_code_and_more'),
        ('inventory', '0002_alter_stockmovement_kind'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.UUIDField(default=core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('device_code', models.CharField(max_length=60)),
                ('name', models.CharField(blank=True, max_length=120)),
                ('minimum_c', models.DecimalField(decimal_places=1, default=2, max_digits=4)),
                ('maximum_c', models.DecimalField(decimal_places=1, default=8, max_digits=4)),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sensors', to='inventory.location')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.organization')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'inventory_sensor',
            },
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.UUIDField(default=core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('celsius', models.DecimalField(decimal_places=1, max_digits=4)),
                ('recorded_at', models.DateTimeField()),
                ('was_buffered', models.BooleanField(default=False)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='readings', to='inventory.sensor')),
            ],
            options={
                'db_table': 'inventory_reading',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='Excursion',
            fields=[
                ('id', models.UUIDField(default=core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('peak_celsius', models.DecimalField(decimal_places=1, max_digits=4)),
                ('minimum_celsius', models.DecimalField(decimal_places=1, max_digits=4)),
                ('reading_count', models.IntegerField(default=0)),
                ('quarantined_base', models.BigIntegerField(default=0)),
                ('batches_affected', models.IntegerField(default=0)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.organization')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='excursions', to='inventory.sensor')),
            ],
            options={
                'db_table': 'inventory_excursion',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddIndex(
            model_name='sensor',
            index=models.Index(fields=['organization', 'location'], name='inventory_s_organiz_c6044a_idx'),
        ),
        migrations.AddConstraint(
            model_name='sensor',
            constraint=models.UniqueConstraint(fields=('organization', 'device_code'), name='uq_sensor_device'),
        ),
        migrations.AddIndex(
            model_name='reading',
            index=models.Index(fields=['sensor', '-recorded_at'], name='inventory_r_sensor__c39cf3_idx'),
        ),
        migrations.AddConstraint(
            model_name='reading',
            constraint=models.UniqueConstraint(fields=('sensor', 'recorded_at'), name='uq_reading_at'),
        ),
        migrations.AddIndex(
            model_name='excursion',
            index=models.Index(fields=['organization', '-started_at'], name='inventory_e_organiz_f0163b_idx'),
        ),
    ]
