# Generated by Django 5.1.5 on 2026-08-12 19:46

import core.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('kind', models.CharField(choices=[('PICKING_TICKET', 'Picking ticket'), ('DELIVERY_NOTE', 'Delivery note'), ('TAX_INVOICE', 'Commercial tax invoice'), ('PROFORMA', 'Proforma invoice'), ('GOODS_RECEIPT', 'Goods receipt note'), ('CONTROLLED_TRANSFER', 'Controlled substance transfer'), ('CREDIT_NOTE', 'Credit note'), ('DEBIT_NOTE', 'Debit note'), ('WRITE_OFF', 'Inventory write-off certificate')], max_length=25)),
                ('number', models.CharField(max_length=30)),
                ('subject_type', models.CharField(max_length=80)),
                ('subject_id', models.UUIDField(blank=True, null=True)),
                ('context', models.JSONField(default=dict)),
                ('html', models.TextField(blank=True)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/')),
                ('sha256', models.CharField(blank=True, max_length=64)),
                ('version', models.IntegerField(default=1)),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.organization')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by', to='documents.document')),
            ],
            options={
                'db_table': 'documents_document',
                'ordering': ['-issued_at'],
                'indexes': [models.Index(fields=['organization', 'kind'], name='documents_d_organiz_f73a2f_idx'), models.Index(fields=['subject_type', 'subject_id'], name='documents_d_subject_6fb778_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'kind', 'number', 'version'), name='uq_document_number_version')],
            },
        ),
    ]
