# Generated by Django 5.1.5 on 2026-08-13 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='kind',
            field=models.CharField(choices=[('PICKING_TICKET', 'Picking ticket'), ('DELIVERY_NOTE', 'Delivery note'), ('TAX_INVOICE', 'Commercial tax invoice'), ('PROFORMA', 'Proforma invoice'), ('GOODS_RECEIPT', 'Goods receipt note'), ('CONTROLLED_TRANSFER', 'Controlled substance transfer'), ('CREDIT_NOTE', 'Credit note'), ('DEBIT_NOTE', 'Debit note'), ('WRITE_OFF', 'Inventory write-off certificate'), ('CLAIM', 'Insurance claim')], max_length=25),
        ),
    ]
