# Generated by Django 5.1.5 on 2026-08-12 21:39

import core.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alertacknowledgement_alertrule'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlledQuota',
            fields=[
                ('id', models.UUIDField(default=core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('schedule', models.CharField(max_length=20)),
                ('period', models.CharField(choices=[('MONTH', 'Calendar month'), ('QUARTER', 'Calendar quarter'), ('YEAR', 'Calendar year')], default='MONTH', max_length=10)),
                ('limit_base', models.BigIntegerField(default=0)),
                ('authority_reference', models.CharField(blank=True, max_length=60)),
                ('effective_from', models.DateField(default=django.utils.timezone.localdate)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.organization')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_controlled_quota',
                'indexes': [models.Index(fields=['organization', 'schedule', 'effective_from'], name='core_contro_organiz_72883b_idx')],
            },
        ),
    ]
