# Generated by Django 5.1.5 on 2026-08-13 08:03

import core.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_controlledquota'),
        ('inventory', '0002_alter_stockmovement_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('code', models.CharField(max_length=60)),
                ('name', models.CharField(blank=True, max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('agent_version', models.CharField(blank=True, max_length=20)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.branch')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.location')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.organization')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_device',
            },
        ),
        migrations.CreateModel(
            name='SyncEnvelope',
            fields=[
                ('id', models.UUIDField(default=core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('client_id', models.CharField(max_length=64)),
                ('sequence', models.BigIntegerField(default=0)),
                ('kind', models.CharField(max_length=40)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('APPLIED', 'Applied'), ('DUPLICATE', 'Already applied'), ('FAILED', 'Failed')], max_length=12)),
                ('result', models.JSONField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('occurred_at', models.DateTimeField()),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='envelopes', to='core.device')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.organization')),
            ],
            options={
                'db_table': 'core_sync_envelope',
                'ordering': ['device', 'sequence'],
            },
        ),
        migrations.AddConstraint(
            model_name='device',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='uq_device_code'),
        ),
        migrations.AddIndex(
            model_name='syncenvelope',
            index=models.Index(fields=['device', 'sequence'], name='core_sync_e_device__3ddb60_idx'),
        ),
        migrations.AddIndex(
            model_name='syncenvelope',
            index=models.Index(fields=['organization', 'status'], name='core_sync_e_organiz_317b3d_idx'),
        ),
        migrations.AddConstraint(
            model_name='syncenvelope',
            constraint=models.UniqueConstraint(fields=('organization', 'client_id'), name='uq_sync_client_id'),
        ),
    ]
